---
repos:
  - repo: local
    hooks:
      - id: black
        name: Python Black
        entry: black
        args: [--check]
        language: system
        types: [file, python, text]
      - id: flake8
        name: Python Flake8
        entry: flake8
        language: system
        types: [file, python, text]
      - id: shellcheck
        name: Shell Check
        entry: shellcheck
        language: system
        types: [file, bash, text]
      - id: yamllint
        name: YAML Lint
        entry: yamllint
        language: system
        types: [file, yaml]
